var abi = [ { "constant": true, "inputs": [], "name": "resolver", "outputs": [ { "name": "", "type": "address" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0x04f3bcec" }, { "constant": true, "inputs": [], "name": "rns", "outputs": [ { "name": "", "type": "address" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0x663b44c5" }, { "constant": true, "inputs": [], "name": "whitelist", "outputs": [ { "name": "", "type": "address" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0x93e59dc1" }, { "constant": true, "inputs": [], "name": "price", "outputs": [ { "name": "", "type": "uint256" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0xa035b1fe" }, { "constant": true, "inputs": [], "name": "admin", "outputs": [ { "name": "", "type": "address" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0xf851a440" }, { "constant": true, "inputs": [], "name": "rootNode", "outputs": [ { "name": "", "type": "bytes32" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0xfaff50a8" }, { "constant": true, "inputs": [], "name": "token", "outputs": [ { "name": "", "type": "address" } ], "payable": false, "stateMutability": "view", "type": "function", "signature": "0xfc0c546a" }, { "inputs": [ { "name": "_rns", "type": "address" }, { "name": "_resolver", "type": "address" }, { "name": "_whitelist", "type": "address" }, { "name": "_token", "type": "address" }, { "name": "_rootNode", "type": "bytes32" } ], "payable": false, "stateMutability": "nonpayable", "type": "constructor", "signature": "constructor" }, { "constant": false, "inputs": [ { "name": "label", "type": "bytes32" }, { "name": "addr", "type": "address" } ], "name": "register", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function", "signature": "0xd22057a9" }, { "constant": false, "inputs": [ { "name": "_price", "type": "uint256" } ], "name": "setPrice", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function", "signature": "0x91b7f5ed" }, { "constant": false, "inputs": [ { "name": "receiver", "type": "address" }, { "name": "_token", "type": "address" } ], "name": "retriveTokens", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function", "signature": "0x22c9271a" } ]

var build = function(client, address) {  
  return new client.eth.Contract(abi, address);
};

module.exports = {
  abi: abi,
  build: build
}