var abi = [{"constant": true,"inputs": [],"name": "owner","outputs": [{"name": "","type": "address"}],"payable": false,"stateMutability": "view","type": "function","signature": "0x8da5cb5b"},{"constant": true,"inputs": [{"name": "","type": "address"}],"name": "whitelistedUntil","outputs": [{"name": "","type": "uint256"}],"payable": false,"stateMutability": "view","type": "function","signature": "0x8f6ca87c"},{"constant": true,"inputs": [],"name": "whitelistedTime","outputs": [{"name": "","type": "uint256"}],"payable": false,"stateMutability": "view","type": "function","signature": "0x903eab92"},{"constant": true,"inputs": [{"name": "","type": "address"}],"name": "isManager","outputs": [{"name": "","type": "bool"}],"payable": false,"stateMutability": "view","type": "function","signature": "0xf3ae2415"},{"inputs": [],"payable": false,"stateMutability": "nonpayable","type": "constructor","signature": "constructor"},{"constant": false,"inputs": [{"name": "manager","type": "address"}],"name": "addManager","outputs": [],"payable": false,"stateMutability": "nonpayable","type": "function","signature": "0x2d06177a"},{"constant": false,"inputs": [{"name": "manager","type": "address"}],"name": "removeManager","outputs": [],"payable": false,"stateMutability": "nonpayable","type": "function","signature": "0xac18de43"},{"constant": false,"inputs": [{"name": "whitelisted","type": "address"}],"name": "addWhitelisted","outputs": [],"payable": false,"stateMutability": "nonpayable","type": "function","signature": "0x10154bad"},{"constant": false,"inputs": [{"name": "whitelisted","type": "address"}],"name": "removeWhitelisted","outputs": [],"payable": false,"stateMutability": "nonpayable","type": "function","signature": "0x291d9549"},{"constant": true,"inputs": [{"name": "whitelisted","type": "address"}],"name": "isWhitelisted","outputs": [{"name": "","type": "bool"}],"payable": false,"stateMutability": "view","type": "function","signature": "0x3af32abf"},{"constant": false,"inputs": [{"name": "time","type": "uint256"}],"name": "setExpirationTime","outputs": [],"payable": false,"stateMutability": "nonpayable","type": "function","signature": "0xc0cc365d"}]
var build = function(client, address) {  
  return new client.eth.Contract(abi, address);
};

module.exports = {
  abi: abi,
  build: build
}
